### ISSUE TITLE
Option to not include semicolons

### ISSUE THREAD

**Issue by thejmazz** [epilande/vim-react-snippets#1]
is this possible?

otherwise working great, good work!

**Comment by epilande** [comment]
Hi @thejmazz, I would suggest forking this repo & removing the semicolons per snippet.

Thanks 😄 👍

**Comment by thejmazz** [comment]
Aha yes that is what I was going to do :p

thought maybe

```
let g:ReactSnippetsSemicolon=0
```

could be possible.

I'll play with the idea in a fork and PR if it is :)

cheers
