### ISSUE TITLE
rfc doesn't expand to arrow function

### ISSUE THREAD

**Issue by Strangehill** [epilande/vim-react-snippets#9]
despite README snippet showing it that way.

**Comment by Strangehill** [comment]
I'd love to see the snippet change, but it seems it had been an arrow function till a year ago when it was changed. So perhaps the README needs the change.

**Comment by epilande** [comment]
Hey @Strangehill, ahh good catch! 
The README needs to be updated.

This project aims to follow airbnb's javascript guideline (see [Class vs React.createClass vs stateless](https://github.com/airbnb/javascript/tree/master/react#class-vs-reactcreateclass-vs-stateless)).
